name: poi_cicd

env:
  poi_path: apis/poi/**
  registry: docker.pkg.github.com
  repository: hattan/openhack-devops-team-gh/api-poi
  docker_path: apis/poi/web
  staging_url: ""
  prod_url: ""
  resource_group: ""
  webapp_name: ""
  build_name: ""

on:
  push:
   branches: [main]
   paths:
    - apis/poi/**
    - .gihtub/workflow/poi_ci.yml
  pull_request:
    branches: [main]
    paths:
    - apis/poi/**
    - .gihtub/workflow/poi_ci.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '3.1.202'
    
    - name: Add Code Coverage
      working-directory: apis/poi/test/UnitTests
      run: dotnet add pakcage coverlet.msbuild

    - name: Install Dependencies
      run: dotnet restore apis/poi/web/*.csproj

    - name: .NET Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj

    - name: .NET Build Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj

    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
        base-path: apis/poi
        flag-name: Unit